version: "3.8"

services:
  database:
    image: postgres:15
    container_name: paytm
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: paytm
    ports:
      - "5432:5432"
    volumes:
      - paytm_data:/var/lib/postgresql/data
    networks:
      - paytm_network

volumes:
  paytm_data:

networks:
  paytm_network:
